# Generated by Django 3.2.5 on 2021-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
